package View;

public class CadastroConcluido extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form CadastroConcluido
     */
    public CadastroConcluido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jButton1.setBackground(new java.awt.Color(153, 105, 128));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(55, 12, 33));
        jButton1.setText("CONTINUAR");
        jButton1.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 186, 206));

        jPanel7.setBackground(new java.awt.Color(253, 234, 255));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Desktop\\FERNANDA ESCOLA 2023\\POO\\ProjetoWinxStudies\\CadastroConcluido.png")); // NOI18N
        jLabel11.setText("jLabel1");

        jButton7.setBackground(new java.awt.Color(164, 137, 167));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(62, 35, 65));
        jButton7.setText("CONTINUAR");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(62, 35, 65));
        jLabel12.setText("Cadastro concluido!");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel12))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
	 * @return the jButton1
	 */
	public javax.swing.JButton getjButton1() {
		return jButton1;
	}

	/**
	 * @param jButton1 the jButton1 to set
	 */
	public void setjButton1(javax.swing.JButton jButton1) {
		this.jButton1 = jButton1;
	}

	/**
	 * @return the jButton2
	 */
	public javax.swing.JButton getjButton2() {
		return jButton2;
	}

	/**
	 * @param jButton2 the jButton2 to set
	 */
	public void setjButton2(javax.swing.JButton jButton2) {
		this.jButton2 = jButton2;
	}

	/**
	 * @return the jButton3
	 */
	public javax.swing.JButton getjButton3() {
		return jButton3;
	}

	/**
	 * @param jButton3 the jButton3 to set
	 */
	public void setjButton3(javax.swing.JButton jButton3) {
		this.jButton3 = jButton3;
	}

	/**
	 * @return the jButton4
	 */
	public javax.swing.JButton getjButton4() {
		return jButton4;
	}

	/**
	 * @param jButton4 the jButton4 to set
	 */
	public void setjButton4(javax.swing.JButton jButton4) {
		this.jButton4 = jButton4;
	}

	/**
	 * @return the jButton5
	 */
	public javax.swing.JButton getjButton5() {
		return jButton5;
	}

	/**
	 * @param jButton5 the jButton5 to set
	 */
	public void setjButton5(javax.swing.JButton jButton5) {
		this.jButton5 = jButton5;
	}

	/**
	 * @return the jButton6
	 */
	public javax.swing.JButton getjButton6() {
		return jButton6;
	}

	/**
	 * @param jButton6 the jButton6 to set
	 */
	public void setjButton6(javax.swing.JButton jButton6) {
		this.jButton6 = jButton6;
	}

	/**
	 * @return the jButton7
	 */
	public javax.swing.JButton getjButton7() {
		return jButton7;
	}

	/**
	 * @param jButton7 the jButton7 to set
	 */
	public void setjButton7(javax.swing.JButton jButton7) {
		this.jButton7 = jButton7;
	}

	/**
	 * @return the jLabel1
	 */
	public javax.swing.JLabel getjLabel1() {
		return jLabel1;
	}

	/**
	 * @param jLabel1 the jLabel1 to set
	 */
	public void setjLabel1(javax.swing.JLabel jLabel1) {
		this.jLabel1 = jLabel1;
	}

	/**
	 * @return the jLabel10
	 */
	public javax.swing.JLabel getjLabel10() {
		return jLabel10;
	}

	/**
	 * @param jLabel10 the jLabel10 to set
	 */
	public void setjLabel10(javax.swing.JLabel jLabel10) {
		this.jLabel10 = jLabel10;
	}

	/**
	 * @return the jLabel11
	 */
	public javax.swing.JLabel getjLabel11() {
		return jLabel11;
	}

	/**
	 * @param jLabel11 the jLabel11 to set
	 */
	public void setjLabel11(javax.swing.JLabel jLabel11) {
		this.jLabel11 = jLabel11;
	}

	/**
	 * @return the jLabel12
	 */
	public javax.swing.JLabel getjLabel12() {
		return jLabel12;
	}

	/**
	 * @param jLabel12 the jLabel12 to set
	 */
	public void setjLabel12(javax.swing.JLabel jLabel12) {
		this.jLabel12 = jLabel12;
	}

	/**
	 * @return the jLabel2
	 */
	public javax.swing.JLabel getjLabel2() {
		return jLabel2;
	}

	/**
	 * @param jLabel2 the jLabel2 to set
	 */
	public void setjLabel2(javax.swing.JLabel jLabel2) {
		this.jLabel2 = jLabel2;
	}

	/**
	 * @return the jLabel3
	 */
	public javax.swing.JLabel getjLabel3() {
		return jLabel3;
	}

	/**
	 * @param jLabel3 the jLabel3 to set
	 */
	public void setjLabel3(javax.swing.JLabel jLabel3) {
		this.jLabel3 = jLabel3;
	}

	/**
	 * @return the jLabel4
	 */
	public javax.swing.JLabel getjLabel4() {
		return jLabel4;
	}

	/**
	 * @param jLabel4 the jLabel4 to set
	 */
	public void setjLabel4(javax.swing.JLabel jLabel4) {
		this.jLabel4 = jLabel4;
	}

	/**
	 * @return the jLabel5
	 */
	public javax.swing.JLabel getjLabel5() {
		return jLabel5;
	}

	/**
	 * @param jLabel5 the jLabel5 to set
	 */
	public void setjLabel5(javax.swing.JLabel jLabel5) {
		this.jLabel5 = jLabel5;
	}

	/**
	 * @return the jLabel6
	 */
	public javax.swing.JLabel getjLabel6() {
		return jLabel6;
	}

	/**
	 * @param jLabel6 the jLabel6 to set
	 */
	public void setjLabel6(javax.swing.JLabel jLabel6) {
		this.jLabel6 = jLabel6;
	}

	/**
	 * @return the jLabel7
	 */
	public javax.swing.JLabel getjLabel7() {
		return jLabel7;
	}

	/**
	 * @param jLabel7 the jLabel7 to set
	 */
	public void setjLabel7(javax.swing.JLabel jLabel7) {
		this.jLabel7 = jLabel7;
	}

	/**
	 * @return the jLabel8
	 */
	public javax.swing.JLabel getjLabel8() {
		return jLabel8;
	}

	/**
	 * @param jLabel8 the jLabel8 to set
	 */
	public void setjLabel8(javax.swing.JLabel jLabel8) {
		this.jLabel8 = jLabel8;
	}

	/**
	 * @return the jLabel9
	 */
	public javax.swing.JLabel getjLabel9() {
		return jLabel9;
	}

	/**
	 * @param jLabel9 the jLabel9 to set
	 */
	public void setjLabel9(javax.swing.JLabel jLabel9) {
		this.jLabel9 = jLabel9;
	}

	/**
	 * @return the jPanel1
	 */
	public javax.swing.JPanel getjPanel1() {
		return jPanel1;
	}

	/**
	 * @param jPanel1 the jPanel1 to set
	 */
	public void setjPanel1(javax.swing.JPanel jPanel1) {
		this.jPanel1 = jPanel1;
	}

	/**
	 * @return the jPanel2
	 */
	public javax.swing.JPanel getjPanel2() {
		return jPanel2;
	}

	/**
	 * @param jPanel2 the jPanel2 to set
	 */
	public void setjPanel2(javax.swing.JPanel jPanel2) {
		this.jPanel2 = jPanel2;
	}

	/**
	 * @return the jPanel3
	 */
	public javax.swing.JPanel getjPanel3() {
		return jPanel3;
	}

	/**
	 * @param jPanel3 the jPanel3 to set
	 */
	public void setjPanel3(javax.swing.JPanel jPanel3) {
		this.jPanel3 = jPanel3;
	}

	/**
	 * @return the jPanel4
	 */
	public javax.swing.JPanel getjPanel4() {
		return jPanel4;
	}

	/**
	 * @param jPanel4 the jPanel4 to set
	 */
	public void setjPanel4(javax.swing.JPanel jPanel4) {
		this.jPanel4 = jPanel4;
	}

	/**
	 * @return the jPanel5
	 */
	public javax.swing.JPanel getjPanel5() {
		return jPanel5;
	}

	/**
	 * @param jPanel5 the jPanel5 to set
	 */
	public void setjPanel5(javax.swing.JPanel jPanel5) {
		this.jPanel5 = jPanel5;
	}

	/**
	 * @return the jPanel6
	 */
	public javax.swing.JPanel getjPanel6() {
		return jPanel6;
	}

	/**
	 * @param jPanel6 the jPanel6 to set
	 */
	public void setjPanel6(javax.swing.JPanel jPanel6) {
		this.jPanel6 = jPanel6;
	}

	/**
	 * @return the jPanel7
	 */
	public javax.swing.JPanel getjPanel7() {
		return jPanel7;
	}

	/**
	 * @param jPanel7 the jPanel7 to set
	 */
	public void setjPanel7(javax.swing.JPanel jPanel7) {
		this.jPanel7 = jPanel7;
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LoginView logar=new LoginView();
        logar.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroConcluido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroConcluido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}